### ISSUE TITLE
Error running test.py

### ISSUE THREAD

**Issue by Mascia** [svishwa/crowdcount-cascaded-mtl#4]
When trying to run test.py I get the following message: 
  File "test.py", line 4, in <module>
    from src.crowd_count import CrowdCounter
  File "ROOT/crowdcount-cascaded-mtl/src/crowd_count.py", line 5, in <module>
    import network
ModuleNotFoundError: No module named 'network'

Thanks in advance for your help

**Comment by Lareinahe** [comment]
I think you should changed this line into "from src import network".

**Comment by so-as** [comment]
@Mascia @Lareinahe .Hi, when I run test.py, I met some error as below: 
![image](https://user-images.githubusercontent.com/6880626/35663624-27abbbd6-0759-11e8-8087-d4333c3efb76.png)
have you get this work well done and get right result? thank you

**Comment by CelineZhou03** [comment]
cuda runtime error!
When trying to run test.py I get the following message:
(pytorch) zhouyao@wb-i36g:~/crowdcount-cascaded-mtl$ python test.py --gpu 0
Pre-loading the data. This may take a while...
Loaded  100 / 182
Completed laoding  182 files
/home/zhouyao/anaconda3/envs/pytorch/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argumen         t of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/zhouyao/crowdcount-cascaded-mtl/src/crowd_count.py:25: UserWarning: Implicit dimension choice for softmax has been deprecated.          Change the call to include dim=X as an argument.
  density_cls_prob = F.softmax(density_cls_score)
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generic/THCTensorCopy.c line=70 error=77 : an ill         egal memory access was encountered
Traceback (most recent call last):
  File "test.py", line 45, in <module>
    density_map = density_map.data.cpu().numpy()
  File "/home/zhouyao/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/tensor.py", line 35, in cpu
    return self.type(getattr(torch, self.__class__.__name__))
  File "/home/zhouyao/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/cuda/__init__.py", line 370, in type
    return super(_CudaBase, self).type(*args, **kwargs)
  File "/home/zhouyao/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/_utils.py", line 38, in _type
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1513363039688/work/t         orch/lib/THC/generic/THCTensorCopy.c:70

Any suggestions for what might be wrong?

**Comment by hiramustafa77** [comment]
did it work I am getting the same error

**Comment by hiramustafa77** [comment]
> I think you should changed this line into "from src import network
this is how it has been done but still this is giving same error 
Kindly help I am getting the same error
